#!/usr/bin/env node
/**
 * Build-time data resolution script
 *
 * Reads data configuration and generates resolved-data.ts
 * - With BUILD_DATA_KEY matching secret file's passphrase: uses real data
 * - Without valid key: uses sanitized placeholder data
 *
 * Usage:
 *   node scripts/resolve-data.mjs
 *   BUILD_DATA_KEY=your-passphrase node scripts/resolve-data.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const CONFIG_DIR = path.join(projectRoot, 'src', 'config');
const SANITIZED_PATH = path.join(CONFIG_DIR, 'data.yaml');
const SECRET_PATH = path.join(CONFIG_DIR, 'data.secret.yaml');
const OUTPUT_PATH = path.join(CONFIG_DIR, 'resolved-data.ts');

const BUILD_KEY = process.env.BUILD_DATA_KEY || '';

/**
 * Simple YAML parser for our specific format (nested key-value pairs)
 * Handles:
 *   key: "value"
 *   category:
 *     subkey: "value"
 */
function parseSimpleYaml(content) {
  const result = {};
  const lines = content.split('\n');
  let currentSection = null;

  for (const line of lines) {
    // Skip empty lines and comments
    if (!line.trim() || line.trim().startsWith('#')) {
      continue;
    }

    // Check indentation level
    const indent = line.search(/\S/);
    const trimmed = line.trim();

    // Check for key: value or key: "value"
    const colonIndex = trimmed.indexOf(':');
    if (colonIndex === -1) continue;

    const key = trimmed.slice(0, colonIndex).trim();
    const valueStr = trimmed.slice(colonIndex + 1).trim();

    if (indent === 0) {
      // Top-level key
      if (valueStr === '' || valueStr === '|' || valueStr === '>') {
        // This is a section header
        currentSection = key;
        result[currentSection] = {};
      } else {
        // This is a top-level key-value
        currentSection = null;
        result[key] = parseValue(valueStr);
      }
    } else if (currentSection && indent > 0) {
      // Nested key under current section
      result[currentSection][key] = parseValue(valueStr);
    }
  }

  return result;
}

/**
 * Parse a YAML value (handles quoted strings and bare values)
 */
function parseValue(str) {
  str = str.trim();

  // Handle quoted strings
  if ((str.startsWith('"') && str.endsWith('"')) ||
      (str.startsWith("'") && str.endsWith("'"))) {
    return str.slice(1, -1);
  }

  // Handle numbers
  if (!isNaN(str) && str !== '') {
    return Number(str);
  }

  // Handle booleans
  if (str === 'true') return true;
  if (str === 'false') return false;
  if (str === 'null') return null;

  return str;
}

/**
 * Flatten nested data into a single-level object with prefixed keys
 * e.g., { systems: { TRADE_SYSTEM: "TPS" } } => { systems_TRADE_SYSTEM: "TPS" }
 */
function flattenData(data, excludeKeys = ['passphrase']) {
  const result = {};

  for (const [category, values] of Object.entries(data)) {
    if (excludeKeys.includes(category)) continue;

    if (typeof values === 'object' && values !== null) {
      for (const [key, value] of Object.entries(values)) {
        result[`${category}_${key}`] = value;
      }
    } else {
      result[category] = values;
    }
  }

  return result;
}

/**
 * Generate TypeScript file content
 */
function generateTypeScript(data, isRealData) {
  const flatData = flattenData(data);

  return `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/resolve-data.mjs at build time
// ${isRealData ? 'Contains REAL data (passphrase matched)' : 'Contains SANITIZED data (no valid passphrase)'}

export const isRealData = ${isRealData};

export const data = ${JSON.stringify(flatData, null, 2)} as const;

// Categorized access
export const systems = ${JSON.stringify(data.systems || {}, null, 2)} as const;
export const standards = ${JSON.stringify(data.standards || {}, null, 2)} as const;
export const organizations = ${JSON.stringify(data.organizations || {}, null, 2)} as const;
export const people = ${JSON.stringify(data.people || {}, null, 2)} as const;
export const metrics = ${JSON.stringify(data.metrics || {}, null, 2)} as const;
export const amounts = ${JSON.stringify(data.amounts || {}, null, 2)} as const;
export const timeframes = ${JSON.stringify(data.timeframes || {}, null, 2)} as const;
export const percentages = ${JSON.stringify(data.percentages || {}, null, 2)} as const;
export const scale = ${JSON.stringify(data.scale || {}, null, 2)} as const;

// Type for all data keys
export type DataKey = keyof typeof data;
`;
}

// Main execution
console.log('[resolve-data] Starting data resolution...');

let resolvedData = null;
let isRealData = false;

// Try to load secret data if BUILD_KEY is provided
if (BUILD_KEY) {
  console.log('[resolve-data] BUILD_DATA_KEY provided, checking for secret file...');

  if (fs.existsSync(SECRET_PATH)) {
    try {
      const secretContent = fs.readFileSync(SECRET_PATH, 'utf8');
      const secretData = parseSimpleYaml(secretContent);

      if (secretData.passphrase === BUILD_KEY) {
        console.log('[resolve-data] Passphrase MATCHED - using real data');
        resolvedData = secretData;
        isRealData = true;
      } else {
        console.log('[resolve-data] Passphrase did NOT match');
      }
    } catch (err) {
      console.error('[resolve-data] Error reading secret file:', err.message);
    }
  } else {
    console.log('[resolve-data] Secret file not found at:', SECRET_PATH);
  }
}

// Fall back to sanitized data
if (!resolvedData) {
  console.log('[resolve-data] Using sanitized data from:', SANITIZED_PATH);

  if (!fs.existsSync(SANITIZED_PATH)) {
    console.error('[resolve-data] ERROR: Sanitized data file not found!');
    process.exit(1);
  }

  const sanitizedContent = fs.readFileSync(SANITIZED_PATH, 'utf8');
  resolvedData = parseSimpleYaml(sanitizedContent);
}

// Generate output file
const outputContent = generateTypeScript(resolvedData, isRealData);
fs.writeFileSync(OUTPUT_PATH, outputContent);

console.log('[resolve-data] Generated:', OUTPUT_PATH);
console.log('[resolve-data] Data type:', isRealData ? 'REAL' : 'SANITIZED');
console.log('[resolve-data] Done!');
